version: "3"
services:
  postgres:
    container_name: servian
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_DB: servian
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
   ports:
    - "5434:5434"